import { describe, it, expect } from 'vitest';
import { analyseSheetedSvg, splitIntoSheets } from '../src/utils/sheetedSvg';
import { importSVG } from '../src/utils/svgImporter';
import { clearGeomBBoxCache } from '../src/utils/geom';

/**
 * Mesh writes a multi-sheet cut as one SVG with the sheets stacked vertically.
 * Opened flat that is a drawing three times taller than the stock, two thirds
 * of it off the material — so it is opened as the strip of sheets it is.
 */

const base = { gridSize: 10, snapToGrid: false, origin: 'top-left' as const, machine: 'laser' as const, material: 'plywood' as const };

/** A stand-in for what Mesh emits: N framed sheets, a square on each. */
function meshSvg(count: number, opts: { frames?: boolean; labels?: boolean; thickness?: number } = {}) {
  const W = 600;
  const H = 400;
  const frames = opts.frames ?? true;
  const labels = opts.labels ?? true;
  let svg = `<svg width="${W}mm" height="${H * count}mm" viewBox="0 0 ${W} ${H * count}" xmlns="http://www.w3.org/2000/svg">\n`;
  svg += `  <!-- Generated by PhysBox Laser Cut Engine -->\n`;
  svg += `  <!-- Settings: Joint=finger, Thickness=${(opts.thickness ?? 3).toFixed(1)}mm, Kerf=0.15mm, Scale=100%, Relief=none -->\n`;
  for (let s = 0; s < count; s++) {
    const y = s * H;
    if (frames) {
      svg += `  <rect x="0" y="${y}" width="${W}" height="${H}" fill="none" stroke="#94A3B8" stroke-width="0.5" stroke-dasharray="4 4" />\n`;
      if (labels) {
        svg += `  <text x="10" y="${y + 20}" fill="#64748B" font-size="12">Sheet ${s + 1} (${W}mm x ${H}mm)</text>\n`;
      }
    }
  }
  svg += `  <g id="cut-paths" stroke="#FF0000" stroke-width="0.2" fill="none">\n`;
  for (let s = 0; s < count; s++) {
    const y = s * H + 100;
    svg += `    <path d="M 50 ${y} L 150 ${y} L 150 ${y + 100} L 50 ${y + 100} Z" />\n`;
  }
  svg += `  </g>\n</svg>`;
  return svg;
}

describe('detecting a stack of sheets', () => {
  it('finds the sheets, their size and the stock they were jointed for', () => {
    const found = analyseSheetedSvg(meshSvg(3));
    expect(found).not.toBeNull();
    expect(found!.bands.count).toBe(3);
    expect(found!.bands.thicknessMm).toBe(3);
    expect(found!.bands.kerfMm).toBe(0.15);
    expect(found!.bands.bands.map((b) => [b.top, b.width, b.height])).toEqual([
      [0, 600, 400],
      [400, 600, 400],
      [800, 600, 400],
    ]);
  });

  it('takes the frames and captions out of the drawing', () => {
    const found = analyseSheetedSvg(meshSvg(2))!;
    expect(found.cleanedSvg).not.toContain('stroke-dasharray');
    expect(found.cleanedSvg).not.toContain('Sheet 1');
    // The parts themselves are untouched.
    expect(found.cleanedSvg).toContain('<path');
  });

  it('declines a single-sheet drawing, which needs no splitting', () => {
    expect(analyseSheetedSvg(meshSvg(1))).toBeNull();
  });

  it('declines when the frames were turned off, rather than guessing a pitch', () => {
    // Without frames a stack of sheets and one tall drawing are the same file,
    // and a wrong guess saws a part in half across two pieces of stock.
    expect(analyseSheetedSvg(meshSvg(3, { frames: false }))).toBeNull();
  });

  it('declines an ordinary drawing that happens to have a dashed box in it', () => {
    const svg =
      `<svg width="200mm" height="100mm" viewBox="0 0 200 100" xmlns="http://www.w3.org/2000/svg">` +
      `<rect x="0" y="0" width="80" height="40" fill="none" stroke="#000" stroke-dasharray="2 2"/>` +
      `<rect x="0" y="55" width="120" height="30" fill="none" stroke="#000" stroke-dasharray="2 2"/>` +
      `</svg>`;
    // Two dashed boxes, but different sizes and not on a sheet pitch.
    expect(analyseSheetedSvg(svg)).toBeNull();
  });
});

describe('splitting into sheets', () => {
  it('gives each band its own sheet, at the stock size', () => {
    clearGeomBBoxCache();
    const found = analyseSheetedSvg(meshSvg(3))!;
    const imported = importSVG(found.cleanedSvg);
    const split = splitIntoSheets(imported, found.bands, 'Box', base);

    expect(split.document.width).toBe(600);
    expect(split.document.height).toBe(400);
    expect(split.document.sheets).toHaveLength(2);
    expect(split.perSheet).toEqual([1, 1, 1]);
    expect(split.strays).toBe(0);
  });

  it('lifts each sheet back to the top of its own stock', () => {
    clearGeomBBoxCache();
    const found = analyseSheetedSvg(meshSvg(3))!;
    const split = splitIntoSheets(importSVG(found.cleanedSvg), found.bands, 'Box', base);
    const docs = [split.document, ...(split.document.sheets ?? [])];
    for (const doc of docs) {
      clearGeomBBoxCache();
      const d = doc.elements[0].d!;
      // Every sheet's part sits at the same place on its own stock — y 100..200
      // — rather than 500 or 900 mm down a drawing three sheets tall.
      const ys = [...d.matchAll(/-?\d*\.?\d+\s+(-?\d*\.?\d+)/g)].map((m) => parseFloat(m[1]));
      expect(Math.min(...ys)).toBeCloseTo(100, 1);
      expect(Math.max(...ys)).toBeCloseTo(200, 1);
    }
  });

  it('carries the thickness the panels were jointed for onto every sheet', () => {
    clearGeomBBoxCache();
    const found = analyseSheetedSvg(meshSvg(2, { thickness: 6 }))!;
    const split = splitIntoSheets(importSVG(found.cleanedSvg), found.bands, 'Box', base);
    // A finger joint cut for 6 mm and run on whatever the open document was set
    // to does not go together, and nothing downstream would catch it.
    expect(split.document.stockThickness).toBe(6);
    expect(split.document.sheets![0].stockThickness).toBe(6);
  });

  it('names the sheets so they can be told apart', () => {
    clearGeomBBoxCache();
    const found = analyseSheetedSvg(meshSvg(2))!;
    const split = splitIntoSheets(importSVG(found.cleanedSvg), found.bands, 'Box', base);
    expect(split.document.name).toBe('Box 1');
    expect(split.document.sheets![0].name).toBe('Box 2');
  });

  it('keeps a panel whose tab overhangs the frame on its own sheet', () => {
    clearGeomBBoxCache();
    // A part centred on sheet 2 but poking 5mm above the frame: a finger tab
    // proud of the edge is exactly what tabOverhang produces, and cutting by
    // geometry would saw it off onto sheet 1.
    const svg =
      `<svg width="600mm" height="800mm" viewBox="0 0 600 800" xmlns="http://www.w3.org/2000/svg">` +
      `<rect x="0" y="0" width="600" height="400" fill="none" stroke="#94A3B8" stroke-dasharray="4 4"/>` +
      `<rect x="0" y="400" width="600" height="400" fill="none" stroke="#94A3B8" stroke-dasharray="4 4"/>` +
      `<path d="M 50 395 L 150 395 L 150 600 L 50 600 Z" stroke="#FF0000" fill="none"/>` +
      `</svg>`;
    const found = analyseSheetedSvg(svg)!;
    const split = splitIntoSheets(importSVG(found.cleanedSvg), found.bands, 'Box', base);
    expect(split.perSheet).toEqual([0, 1]);
  });
});

describe('a mixed rack', () => {
  /** Sheets of assorted sizes, stacked — what a rack of offcuts produces. */
  const mixed = () => {
    const sizes = [
      { w: 600, h: 400, t: 18 },
      { w: 300, h: 200, t: 6 },
      { w: 300, h: 200, t: 6 },
    ];
    let y = 0;
    let svg = `<svg width="600mm" height="800mm" viewBox="0 0 600 800" xmlns="http://www.w3.org/2000/svg">\n`;
    svg += `  <!-- Settings: Joint=finger, Thickness=18.0mm, Kerf=0.15mm -->\n`;
    let paths = '';
    for (let i = 0; i < sizes.length; i++) {
      const s = sizes[i];
      svg += `  <rect x="0" y="${y}" width="${s.w}" height="${s.h}" fill="none" stroke="#94A3B8" stroke-dasharray="4 4"/>\n`;
      svg += `  <text x="10" y="${y + 20}" fill="#64748B">Sheet ${i + 1} (${s.w}mm x ${s.h}mm x ${s.t.toFixed(1)}mm)</text>\n`;
      paths += `    <path d="M 50 ${y + 50} L 150 ${y + 50} L 150 ${y + 100} L 50 ${y + 100} Z" stroke="#FF0000" fill="none"/>\n`;
      y += s.h;
    }
    svg += `  <g id="cut-paths">\n${paths}  </g>\n</svg>`;
    return svg;
  };

  it('accepts sheets of different sizes, so a rack of offcuts still opens as a strip', () => {
    // The earlier rule demanded every frame be identical on an exact pitch,
    // which read a mixed rack as "not a stack" and dropped the whole job onto
    // one sheet.
    const found = analyseSheetedSvg(mixed());
    expect(found).not.toBeNull();
    expect(found!.bands.bands.map((b) => [b.width, b.height])).toEqual([
      [600, 400],
      [300, 200],
      [300, 200],
    ]);
  });

  it('gives each sheet the stock it was actually cut from', () => {
    clearGeomBBoxCache();
    const found = analyseSheetedSvg(mixed())!;
    const split = splitIntoSheets(importSVG(found.cleanedSvg), found.bands, 'Box', base);
    const docs = [split.document, ...(split.document.sheets ?? [])];
    expect(docs.map((d) => [d.width, d.height, d.stockThickness])).toEqual([
      [600, 400, 18],
      [300, 200, 6],
      [300, 200, 6],
    ]);
  });

  it('still refuses frames that are not a stack', () => {
    // Two dashed boxes with a gap between them are not sheets; splitting there
    // would saw a part across two pieces of stock.
    const svg =
      `<svg width="600mm" height="900mm" viewBox="0 0 600 900" xmlns="http://www.w3.org/2000/svg">` +
      `<rect x="0" y="0" width="600" height="400" fill="none" stroke="#94A3B8" stroke-dasharray="4 4"/>` +
      `<rect x="0" y="500" width="600" height="400" fill="none" stroke="#94A3B8" stroke-dasharray="4 4"/>` +
      `</svg>`;
    expect(analyseSheetedSvg(svg)).toBeNull();
  });

  it('does not read a two-dimension caption’s height as a thickness', () => {
    // "Sheet 1 (600mm x 400mm)" has no thickness in it; a looser pattern took
    // 400 and put it on the document as 400 mm stock.
    const found = analyseSheetedSvg(meshSvg(2))!;
    expect(found.bands.bands.every((b) => b.thicknessMm === 3)).toBe(true);
  });
});
